TASK: OpenEndedTask

DATASET:
  FEATURE_DATASET:
    TYPE: Vivqav2FeatureDataset
    BATCH_SIZE: 64
    WORKERS: 0
    FEATURE_PATH:
      FEATURES: features\vinvl_vinvl
      SCENE_TEXT: null
      IMAGE: data/ds102/images
    SCENE_TEXT_THRESHOLD: 0.3
  DICT_DATASET:
    TYPE: DictionaryDataset
    BATCH_SIZE: 64
    WORKERS: 0  
    FEATURE_PATH:
      FEATURES: features\vinvl_vinvl
      SCENE_TEXT: null
      IMAGE: data/ds102/images
    SCENE_TEXT_THRESHOLD: 0.3
  SCENE_TEXT_THRESHOLD: 0.3
  VOCAB:
    TYPE: Vocab
    TOKENIZER: null
    MIN_FREQ: 1
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
    BOS_TOKEN: <bos>
    EOS_TOKEN: <eos>
    PAD_TOKEN: <pad>
    UNK_TOKEN: <unk>
    IMG_TOKEN: <img>
    FEAT_TOKEN: <feat>
    BOX_TOKEN: <box>
    QUESTION_TOKEN: <question>
    ANSWER_TOKEN: <answer>
    JSON_PATH:
      TRAIN: data/ds102/train.json
      DEV: data/ds102/dev.json
      TEST: data/ds102/test.json
  JSON_PATH:
      TRAIN: data/ds102/train.json
      DEV: data/ds102/dev.json
      TEST: data/ds102/test.json
TRAINING:
  CHECKPOINT_PATH: saved_models
  LEARNING_RATE: 1.
  RL_LEARNING_RATE: 0.00005
  WARMUP: 10000
  SCORE: CIDEr
  GET_SCORES: True
  TRAINING_BEAM_SIZE: 5
  EVALUATING_BEAM_SIZE: 3
  PATIENCE: 5
  VERBOSE_SCORES:
    - CIDEr
    - BLEU
    - ROUGE
    - Accuracy
    - F1
    - Precision
    - Recall

MODEL:
  ARCHITECTURE: IterativeHierarchicalCoAttention
  NAME: iterative_hierarchical_co_attention_ds102_new_data
  DEVICE: cuda 
  D_MODEL: 512
  VISION_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    D_FEATURE: 2048
    D_MODEL: 512
    DROPOUT: 0.1
  TEXT_EMBEDDING:
    ARCHITECTURE: UsualEmbedding
    D_MODEL: 300
    D_EMBEDDING: 300
    DROPOUT: 0.1
    WORD_EMBEDDING: Null
    WORD_EMBEDDING_CACHE: null
  HIERARCHICAL:
    D_MODEL: 512
    WORD_EMBEDDING_DIM: 300
    N_GRAMS:
     - 1
     - 2
     - 3
     - 4
  ENCODER:
    ARCHITECTURE: CoAttentionEncoder
    D_MODEL: 512
    LAYERS: 8
    VISION_LANGUAGE_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: .1
    LANGUAGE_VISION_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: .1
    VISION_SELF_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: .1
    LANGUAGE_SELF_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: .1
  VISION_ATTR_REDUCE:
    D_MODEL: 512
    DROPOUT: 0.1
  TEXT_ATTR_REDUCE:
    D_MODEL: 512
    DROPOUT: 0.1
  DECODER:
    ARCHITECTURE: Decoder
    D_MODEL: 512
    LAYERS: 3
    ATTENTION:
      SELF_ATTENTION:
        ARCHITECTURE: ScaledDotProductAttention
        HEAD: 8
        D_MODEL: 512
        D_KEY: 64
        D_VALUE: 64
        D_FF: 2048
        D_FEATURE: 2048
        USE_AOA: False
        CAN_BE_STATEFUL: True
        DROPOUT: .1
      ENC_ATTENTION:
        ARCHITECTURE: ScaledDotProductAttention
        HEAD: 8
        D_MODEL: 512
        D_KEY: 64
        D_VALUE: 64
        D_FF: 2048
        D_FEATURE: 2048
        USE_AOA: False
        CAN_BE_STATEFUL: False
        DROPOUT: .1
    TEXT_EMBEDDING:
      ARCHITECTURE: UsualEmbedding
      D_MODEL: 512
      D_EMBEDDING: 300
      WORD_EMBEDDING: null
      WORD_EMBEDDING_CACHE: null
      DROPOUT: 0.1

