TASK: TrainingSAAATask

DATASET:
  FEATURE_DATASET:
    TYPE: Vivqav2FeatureDataset
    BATCH_SIZE: 64
    WORKERS: 0
    FEATURE_PATH:
      FEATURES: features\vinvl_vinvl
      SCENE_TEXT: null
      IMAGE: data/ds102/images
    SCENE_TEXT_THRESHOLD: 0.3
  DICT_DATASET:
    TYPE: DictionaryDataset
    BATCH_SIZE: 64
    WORKERS: 0  
    FEATURE_PATH:
      FEATURES: features\vinvl_vinvl
      SCENE_TEXT: null
      IMAGE: data/ds102/images
    SCENE_TEXT_THRESHOLD: 0.3
  SCENE_TEXT_THRESHOLD: 0.3
  VOCAB:
    TYPE: Vocab
    TOKENIZER: null
    MIN_FREQ: 1
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
    BOS_TOKEN: <bos>
    EOS_TOKEN: <eos>
    PAD_TOKEN: <pad>
    UNK_TOKEN: <unk>
    IMG_TOKEN: <img>
    FEAT_TOKEN: <feat>
    BOX_TOKEN: <box>
    QUESTION_TOKEN: <question>
    ANSWER_TOKEN: <answer>
    JSON_PATH:
      TRAIN: data/ds102/train.json
      DEV: data/ds102/dev.json
      TEST: data/ds102/test.json
  JSON_PATH:
      TRAIN: data/ds102/train.json
      DEV: data/ds102/dev.json
      TEST: data/ds102/test.json

TRAINING:
  CHECKPOINT_PATH: saved_models
  LEARNING_RATE: 0.01
  RL_LEARNING_RATE: 0.000005
  WARMUP: 10000
  SCORE: CIDEr
  TRAINING_BEAM_SIZE: 5
  EVALUATING_BEAM_SIZE: 3
  PATIENCE: 10

MODEL:
  ARCHITECTURE: IterativeSAAA
  NAME: iterative_saaa_region_x152++_faster_rcnn_ds102_new_data
  DEVICE: cuda
  D_MODEL: 512
  VISION_PROCESSOR:
    ARCHITECTURE: FeatureEmbedding
    D_FEATURE: 2048
    D_MODEL: 512
    DROPOUT: .1
  TEXT_PROCESSOR:
    D_EMBEDDING: 300
    D_MODEL: 512
    DROPOUT: .1
  ATTENTION:
    ARCHITECTURE: CoAttention
    D_VISION: 512
    D_LANGUAGE: 512
    D_MODEL: 512
    DROPOUT: .1
    GLIMPSES: 2
  MULTIMODAL_FUSION:
    D_MODEL: 512
    D_FF: 2048
    DROPOUT: .1
  DECODER:
    ARCHITECTURE: Decoder
    D_MODEL: 512
    LAYERS: 1
    ATTENTION:
      SELF_ATTENTION:
        ARCHITECTURE: ScaledDotProductAttention
        HEAD: 8
        D_MODEL: 512
        D_KEY: 64
        D_VALUE: 64
        D_FF: 2048
        D_FEATURE: 2048
        USE_AOA: False
        CAN_BE_STATEFUL: True
        DROPOUT: .1
      ENC_ATTENTION:
        ARCHITECTURE: ScaledDotProductAttention
        HEAD: 8
        D_MODEL: 512
        D_KEY: 64
        D_VALUE: 64
        D_FF: 2048
        D_FEATURE: 2048
        USE_AOA: False
        CAN_BE_STATEFUL: False
        DROPOUT: .1
    TEXT_EMBEDDING:
      ARCHITECTURE: UsualEmbedding
      D_MODEL: 512
      D_EMBEDDING: 300
      WORD_EMBEDDING: null
      WORD_EMBEDDING_CACHE: null
      DROPOUT: 0.1
