TASK: ClassificationTask

DATASET:
  FEATURE_DATASET:
    TYPE: Vivqav2FeatureDataset
    BATCH_SIZE: 64
    WORKERS: 0
    FEATURE_PATH:
      FEATURES: features\vinvl_vinvl
      SCENE_TEXT: null
      IMAGE: data/ds102/images
    SCENE_TEXT_THRESHOLD: 0.3
  DICT_DATASET:
    TYPE: DictionaryDataset
    BATCH_SIZE: 64
    WORKERS: 0  
    FEATURE_PATH:
      FEATURES: features\vinvl_vinvl
      SCENE_TEXT: null
      IMAGE: data/ds102/images
    SCENE_TEXT_THRESHOLD: 0.3
  SCENE_TEXT_THRESHOLD: 0.3
  VOCAB:
    TYPE: VQAv2ClassificationVocab
    TOKENIZER: null
    MIN_FREQ: 1
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
    BOS_TOKEN: <bos>
    EOS_TOKEN: <eos>
    PAD_TOKEN: <pad>
    UNK_TOKEN: <unk>
    IMG_TOKEN: <img>
    FEAT_TOKEN: <feat>
    BOX_TOKEN: <box>
    QUESTION_TOKEN: <question>
    ANSWER_TOKEN: <answer>
    JSON_PATH:
      TRAIN: data/ds102/train.json
      DEV: data/ds102/dev.json
      TEST: data/ds102/test.json
  JSON_PATH:
      TRAIN: data/ds102/train.json
      DEV: data/ds102/dev.json
      TEST: data/ds102/test.json

TRAINING:
  CHECKPOINT_PATH: saved_models
  LEARNING_RATE: 0.0001
  RL_LEARNING_RATE: 0.00005
  WARMUP: 1000
  SCORE: CIDEr
  GET_SCORES: True
  TRAINING_BEAM_SIZE: 5
  EVALUATING_BEAM_SIZE: 3
  PATIENCE: 10
  VERBOSE_SCORES:
    - CIDEr
    - BLEU
    - ROUGE
    - Accuracy
    - F1
    - Precision
    - Recall

MODEL:
  ARCHITECTURE: SimpleMultimodal
  NAME: simple_multimodal_ds102
  DEVICE: cuda
  D_MODEL: 512
  DROPOUT: 0.1
  VISION_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    D_FEATURE: 2048
    D_MODEL: 512
    DROPOUT: 0.1
  TEXT_EMBEDDING:
    ARCHITECTURE: UsualEmbedding
    D_MODEL: 512
    D_EMBEDDING: 300
    DROPOUT: 0.1
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
